import {
  BarChart3,
  Bell,
  Boxes,
  BrainCircuit,
  FileText,
  FolderKanban,
  HelpCircle,
  LayoutGrid,
  Layers,
  ScrollText,
  Settings,
  Store,
  Ticket,
  User,
  Warehouse,
  Wrench,
} from "lucide-react";
import type { NavItem } from "@/types";

export const navGroups: Record<string, string> = {
  main: "Main",
  operations: "Operations",
  inventory: "Inventory",
  analytics: "Analytics",
  system: "System",
  user: "User",
};

export const navItems: NavItem[] = [
  {
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutGrid,
    description: "Realtime overview",
    group: "main",
  },
  {
    label: "Projects",
    href: "/projects",
    icon: FolderKanban,
    description: "Project registry",
    group: "operations",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Contracts",
    href: "/contracts",
    icon: FileText,
    description: "Vendor + SLA",
    group: "operations",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Maintenance",
    href: "/maintenance",
    icon: Wrench,
    description: "Tickets + repairs",
    group: "operations",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Assets",
    href: "/assets",
    icon: Boxes,
    description: "Inventory registry",
    group: "inventory",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Vendors",
    href: "/vendors",
    icon: Store,
    description: "Vendor directory",
    group: "inventory",
    roles: ["super_admin", "admin", "project_manager"],
  },
  {
    label: "Warehouse",
    href: "/warehouse",
    icon: Warehouse,
    description: "Stock management",
    group: "inventory",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Reports",
    href: "/reports",
    icon: BarChart3,
    description: "Analytics + KPIs",
    group: "analytics",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Intelligence",
    href: "/intelligence",
    icon: BrainCircuit,
    description: "AI health scoring",
    group: "analytics",
    roles: ["super_admin", "admin", "project_manager"],
  },
  {
    label: "Audit",
    href: "/audit",
    icon: ScrollText,
    description: "Compliance logs",
    group: "analytics",
    roles: ["super_admin", "admin", "project_manager"],
  },
  {
    label: "Settings",
    href: "/settings",
    icon: Settings,
    description: "Theme + roles",
    group: "system",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "Hardware Catalog",
    href: "/settings/catalog",
    icon: Layers,
    description: "Types & spec categories",
    group: "system",
    roles: ["super_admin", "admin", "project_manager", "project_admin"],
  },
  {
    label: "My Assets",
    href: "/assets",
    icon: Boxes,
    description: "Your assigned hardware",
    group: "user",
    roles: ["department_user", "staff", "viewer"],
  },
  {
    label: "My Tickets",
    href: "/maintenance",
    icon: Ticket,
    description: "Your support tickets",
    group: "user",
    roles: ["department_user", "staff", "viewer", "technician"],
  },
  {
    label: "Profile",
    href: "/settings",
    icon: User,
    description: "Your profile",
    group: "user",
    roles: ["technician", "department_user", "staff", "viewer"],
  },
  {
    label: "Help",
    href: "/help",
    icon: HelpCircle,
    description: "Support & guides",
    group: "user",
    roles: ["department_user", "staff", "viewer"],
  },
];